version: "3"
services:

  mysql:
    image: mysql
    ports:
      - "3406:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root  
      
  backend: 
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/codekombat?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql
    
      
